### ISSUE TITLE
Some guidelines seem out of date

### ISSUE THREAD

**Issue by cor3ntin** [cplusplus/LEWG#12]
The [design guideline](https://github.com/cplusplus/LEWG/blob/master/library-design-guidelines.md) recommend to use C++03 syntax over C++11 features.

> Where C++ 2003 syntax can be used, that is preferred over C++ 2011 features.

It is not clear to me what that mean exactly, and it seems to be there are benefits to use the latest published standard in the specification whenever beneficial and relevant. Which I think we do, so that guideline may no longer apply?

Other things that seems need changing:

* > Use SFINAE to constrain templates:

It's implementation defined how templates are constrained, and concepts should probably be otherwise preferred? 

* > Operators come in groups: (==, !=), (<, >, <=, >=)

Maybe we should prefer `<=>` whenever applicable
* > Don't use code to specify behavior.

I think we do, sometimes

* > For templates, make it clear what the concepts are.

Should we not prefer exposition-only concepts where applicable?

* > Use clause [structure.specifications] to determine what specification clauses to use.

Might be interesting to mention [P1369](https://wg21.link/p1369r0)

* > Do not use requires clauses or define new language-level concepts until the introduction (section 6) and fundamental concepts (section 7) from the Ranges TS have merged into the IS.

Time to revisit that ?

**Comment by brycelelbach** [comment]
I've archived all of these
